language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - python setup.py install
script:
    - python test/test.py
    - pip -q uninstall python-bcrypt
    - pip install python-bcrypt --force-reinstall
